services:
 php-app:
    build: .
    container_name: php-app
    working_dir: /var/www/symfony
    volumes:
      - ./:/var/www/symfony
      - ./.docker/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: "mysql://app_user:password@db:3306/app_db"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: password
    volumes:
     - db_data:/var/lib/mysql
volumes:
 db_data:
